### ISSUE TITLE
Seed Data base (KH Atom)

### ISSUE THREAD

**Issue by jrueter2** [mif-sge/krankenhaus#13]

**Comment by KarstenAMF** [comment]
Seed following datasets split into regions. One atom symbolizes a region (NRW, Berlin)

**Statistics**
- [ ] Personal (**simulated regions**)
- [ ] Krankenhaus Kosten
- [ ] Einrichtungen Patienten Bundesland 
- [ ] Todesfälle Regional

**Diagnosis datasets (split accordingly to the amounts of atoms)**

- [ ] Pima Indian Diabetes (https://www.kaggle.com/uciml/pima-indians-diabetes-database)
- [ ] Breast Cancer Wisconsin (https://www.kaggle.com/uciml/breast-cancer-wisconsin-data)
- [ ] _Heart Disease Uci (https://www.kaggle.com/ronitf/heart-disease-uci)_ (optional)

**Comment by KarstenAMF** [comment]
Close after #19
