### ISSUE TITLE
create Mockups

### ISSUE THREAD

**Issue by ghaake** [mif-sge/krankenhaus#3]
## Molekül Mockups
 - Layout
 - Login
 - Dashboard
   - Overview (Name, Ort, Betten, Patienten, Öffnungzeiten)
   - Aktuelles Budget
   - Aktuelle Auslastung
 - Modulare Graphenkomponente

**Comment by ghaake** [comment]
Done. In: [8d132c6c2b473c9232c4f178293b7b97b7fe126e]

**Comment by Zakor11** [comment]
Please provide a corrected version of the login-mockup with the password label being aligned correctly.

**Comment by ghaake** [comment]
fixed in f7e5b67
