### ISSUE TITLE
Pflichtenheft (Krankenhaus)

### ISSUE THREAD

**Issue by KarstenAMF** [mif-sge/krankenhaus#9]
- [x] Requires #4 

ToDo:

- Ch2
- Ch3
    - [x] Klassendiagramm (soweit wie möglich) 
    - [x] #7 
- ~~Ch4~~

**Comment by Zakor11** [comment]
Updated initial comment, Ch4 is done by myself, Ch3 requirements specified

**Comment by ghaake** [comment]
Updated Initial Commit 

 #7 is done in [d7bbb074244d68787fdccf5eadc7d06c98f1d7f4]

**Comment by ghaake** [comment]
Updated the component diagram. You can now see in which direction the components interact with each other.
This shall be closed for now.
658e038d7de82cae2e8b09ed98649dae37d414d7
